language: java
jdk: openjdk8
services: docker

jobs:
  include:
    - stage: "dependencies"
      name: "Download Dependencies"
      install: mvn install -Dtest.skip=true
    - stage: "test"
      name: "Testing"
      script: mvn test
    - stage: "docker"
      name: "Build Docker Image"
      script: docker build -t tfm/devsecop/travisci .
    - stage: "publish-rc"
      name: "Publish Release Candidate on Docker Hub"
      before_script: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      script: docker tag tfm/devsecop/travisci $DOCKER_USER/tfm/devsecop/travisci:$TRAVIS_COMMIT-RC
      branches:
        - develop


      #script: docker tag tfm/devsecop/travisci $DOCKER_USER/tfm/devsecop/travisci:$TRAVIS_BUILD_NUMBER-RC

