language: java
jdk: openjdk8
services: docker

env:
  - DOCKER_REPOSITORY="tfm-devsecop"

jobs:
  include:
    - stage: "dependencies"
      name: "Download Dependencies"
      install: mvn install -Dtest.skip=true

    - stage: "test"
      name: "Testing"
      script: mvn test

    - stage: "docker"
      name: "Build Docker Image"
      script: docker build -t $DOCKER_REPOSITORY-travisci .

    - stage: "publish-rc"
      name: "Publish Release Candidate on Docker Hub"
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker tag $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:$TRAVIS_COMMIT-RC
      after_script: docker push $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:$TRAVIS_COMMIT-RC
      if: branch = develop

    - stage: "publish-version"
      name: "Publish Release on Docker Hub"
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker tag $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:latest
      after_script:
        - docker push $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_REPOSITORY-travisci $DOCKER_USER/$DOCKER_REPOSITORY-travisci:latest
      if: branch = main


