language: java
jdk: openjdk8
services: docker

env:
  - DOCKER_REPOSITORY="tfm-devsecop"

jobs:
  include:
    - stage: "dependencies"
      name: "Download Dependencies"
      install: mvn install -Dtest.skip=true

    - stage: "test"
      name: "Testing"
      script: mvn test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: "publish-rc"
      name: "Publish Release Candidate on Docker Hub"
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci:$TRAVIS_COMMIT-RC .
      after_script: docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci
      if: branch = develop

    - stage: "publish-version"
      name: "Publish Release on Docker Hub"
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker tag $DOCKER_REPOSITORY-travisci $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_REPOSITORY-travisci $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci:latest
      after_script:
        - docker push $DOCKER_REPOSITORY-travisci $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_REPOSITORY-travisci $DOCKER_USERNAME/$DOCKER_REPOSITORY-travisci:latest
      if: branch = main


